### ISSUE TITLE
lame arm64 support

### ISSUE THREAD

**Issue by vmatsnev** [Superbil/build-lame-for-iOS#1]
Hi.

Please add 

<pre>
PLATFORM="arm64"
build_lame
</pre>

to your build_ios.sh to give other guys ability to build for arm64.

If some one want to fix it local just change in build_ios.sh next lines

<pre>
# build device version
SDK="iPhoneOS"

PLATFORM="armv7"
build_lame

PLATFORM="armv7s"
build_lame
</pre>

with

<pre>
# build device version
SDK="iPhoneOS"

PLATFORM="armv7"
build_lame

PLATFORM="armv7s"
build_lame

PLATFORM="arm64"
build_lame
</pre>

save and run script.

**Comment by Superbil** [comment]
@vmatsnev Thank you. I added it into script.
