### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ghost** [Superbil/build-lame-for-iOS#2]
Hi

I download the release libmp3lame.a and build my project have many error:

Undefined symbols for architecture x86_64:
  "_lame_close", referenced from:
      ___55-[UserRecording(JSONData) conversionToMP3WithComplete:]_block_invoke in UserRecording+JSONData.o
  "_lame_encode_buffer_interleaved", referenced from:
      ___55-[UserRecording(JSONData) conversionToMP3WithComplete:]_block_invoke in UserRecording+JSONData.o
  "_lame_encode_flush", referenced from:
      ___55-[UserRecording(JSONData) conversionToMP3WithComplete:]_block_invoke in UserRecording+JSONData.o
  "_lame_init", referenced from:
      ___55-[UserRecording(JSONData) conversionToMP3WithComplete:]_block_invoke in UserRecording+JSONData.o
  "_lame_init_params", referenced from:
      ___55-[UserRecording(JSONData) conversionToMP3WithComplete:]_block_invoke in UserRecording+JSONData.o
  "_lame_set_VBR", referenced from:
      ___55-[UserRecording(JSONData) conversionToMP3WithComplete:]_block_invoke in UserRecording+JSONData.o
  "_lame_set_in_samplerate", referenced from:
      ___55-[UserRecording(JSONData) conversionToMP3WithComplete:]_block_invoke in UserRecording+JSONData.o
ld: symbol(s) not found for architecture x86_64

**Comment by ghost** [comment]
fix x86_64 issue.

```
#!/bin/bash
## Mini-Xcode: XCode 6

MIN_VERSION="6.0"

# set default output folder is build
OUTPUT_FOLDER=${PREFIX-build}

# set default compiler
CC=${CC-$(xcrun --find gcc)}
LIPO=${LIPO-$(xcrun --find lipo)}

XCODE_PATH=$(xcode-select -print-path)

# make output folder
mkdir -p $OUTPUT_FOLDER

function build_lame()
{
    make distclean

    # SDK must lower case
    SDK_ROOT=$(xcrun --sdk $(echo ${SDK} | tr '[:upper:]' '[:lower:]') --show-sdk-path)

    ./configure \
        CFLAGS="-arch ${PLATFORM} -pipe -std=c99 -isysroot ${SDK_ROOT} -miphoneos-version-min=${MIN_VERSION}" \
        --host="${HOST}" \
        --enable-static \
        --disable-decoder \
        --disable-frontend \
        --disable-debug \
        --disable-dependency-tracking

    make

    cp "libmp3lame/.libs/libmp3lame.a" "${OUTPUT_FOLDER}/libmp3lame-${PLATFORM}.a"
}

# build simulator version
SDK="iPhoneSimulator"
PLATFORM="i686"
build_lame

HOST="i686-apple-darwin13.1.0"
SDK="iPhoneSimulator"
PLATFORM="x86_64"
build_lame

# build device version
SDK="iPhoneOS"

PLATFORM="armv7"
build_lame

PLATFORM="armv7s"
build_lame

PLATFORM="arm64"
build_lame

# remove old libmp3lame.a or lipo will failed
OUTPUT_LIB=${OUTPUT_FOLDER}/libmp3lame.a
if [ -f $OUTPUT_LIB ]; then
    rm $OUTPUT_LIB
fi

${LIPO} -create ${OUTPUT_FOLDER}/* -output ${OUTPUT_LIB}
```

**Comment by Superbil** [comment]
I fix this problem at https://github.com/Superbil/build-lame-for-iOS/commit/074dd1029d0f91d4570cb394d322765d8ac37d82

Please use last version.
