### ISSUE TITLE
Latest realease (1.2) does not contain x86_64 architecture

### ISSUE THREAD

**Issue by sourceclimber** [Superbil/build-lame-for-iOS#6]
I tried to use your latest release in a Xcode project, but the linker complained that there is no x86_64 version of the library.
I forked your repo and executed the buildscript myselfe and the resulting library contained all architectures.

Could you please look into it and upload a new release in case anyone else runs into this problem ;-)?

**Comment by Superbil** [comment]
Sorry about that, I rebuild the library. Thank you
